apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: foreldrepengesoknad-api
{{#if namespace}}
  namespace: {{namespace}}
{{else}}
  namespace: default
{{/if}} 
  labels:
    team: teamforeldrepenger
spec:
{{#if namespace}}
  accessPolicy:
    outbound:
      external: 
        - host: storage.googleapis.com
        - host: oauth2.googleapis.com
        - host: www.googleapis.com
 {{#if gw}}       
        - host: {{gw}}
 {{/if}}       
      rules: []
  secrets:
    - name: gcp.accesskey
    - name: gcp.secretkey
    - name: oppslag.key
    - name: mottak.key
    - name: historikk.key
    - name: storage.passphrase
    - name: buckets
      type: files
{{/if}}  

  image: {{image}}
  port: 8080
  replicas:
      min: 2
      max: 2
      cpuThresholdPercentage: 50  
  liveness:
      path: /internal/actuator/info
      initialDelay: 60
  readiness:
      path: /internal/actuator/info
      initialDelay: 60  
  prometheus:
      enabled: true
      path: /internal/actuator/prometheus
  replicas:
      min: 2
      max: 2
      cpuThresholdPercentage: 50
  ingresses:
    - {{ingress}}
  resources:
      limits:
        cpu: 1500m
        memory: 3072Mi
      requests:
        cpu: 250m
        memory: 1536Mi 
  vault:
{{#if namespace}}
      enabled: false   
{{else}} 
     enabled: true   
{{/if}} 

  env: 
  {{#each env}}
   - name: "{{@key}}"
     value: "{{this}}"
  {{/each}}
 {{#if namespace}}
  webproxy: false
{{else}}
  webproxy: true
{{/if}} 
