apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{application_name}}
{{#if namespace}}
  namespace: {{namespace}}
{{else}}
  namespace: default
{{/if}} 
  labels:
    team: {{team}}
spec:
  accessPolicy:
    outbound:
      external: 
        - host: storage.googleapis.com
        - host: login.microsoftonline.com
        - host: api-gw-q1.oera.no
      rules :
        - application: fp-uttak-service 
  secrets:
    - name: gcp.accesskey
    - name: gcp.secretkey
    - name: oppslag.key
    - name: mottak.key
    - name: historikk.key
    - name: storage.passphrase
  image: {{version}}
  port: 8080
  replicas:
      min: 2
      max: 2
      cpuThresholdPercentage: 50  
  liveness:
      path: /internal/actuator/info
      initialDelay: 60
  readiness:
      path: /internal/actuator/info
      initialDelay: 60  
  prometheus:
      enabled: true
      path: /internal/actuator/prometheus
  replicas:
      min: 2
      max: 2
      cpuThresholdPercentage: 50
  ingresses:
    - {{ingress}}
  resources:
      limits:
        cpu: 1500m
        memory: 3072Mi
      requests:
        cpu: 250m
        memory: 1536Mi 
  vault:
{{#if namespace}}
      enabled: false   
{{else}} 
     enabled: true   
{{/if}} 
  env: 
  {{#each env}}
   - name: {{@key}}
     value: "{{this}}"
  {{/each}}
  {{#if namespace}}
  webproxy: false
{{else}}
  webproxy: true
{{/if}} 
