apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: foreldrepengesoknad-api
{{#if namespace}}
  namespace: {{namespace}}
{{else}}
  namespace: default
{{/if}} 
  labels:
    team: teamforeldrepenger
    cluster: {{cluster}}
spec:
{{#if gcp}}
    buckets:
      - name: mellomlagring
      - name: foreldrepengesoknad
  accessPolicy:
    outbound:
      external: 
        - host: storage.googleapis.com
        - host: oauth2.googleapis.com
        - host: www.googleapis.com
{{#if gcp}}
        - host: {{gw}}
 {{/if}}       
  envFrom:
     - secret: fppdfgen.key
     - secret: oppslag.key
     - secret: mottak.key
     - secret: historikk.key
     - secret: storage.passphrase
{{/if}}  
  image: {{image}}
  port: 8080
  replicas:
      min: 2
      max: 2
      cpuThresholdPercentage: 50  
  liveness:
      path: /internal/actuator/health/liveness
      initialDelay: 60
  readiness:
      path: /internal/actuator/health/liveness
      initialDelay: 60  
  prometheus:
      enabled: true
      path: /internal/actuator/prometheus
  replicas:
      min: 2
      max: 2
      cpuThresholdPercentage: 50
  ingresses:
{{#each ingresses as |url|}}
    - {{url}}
{{/each}} 
  resources:
      limits:
        cpu: 1500m
        memory: 3072Mi
      requests:
        cpu: 250m
        memory: 1536Mi 
  vault:
{{#if gcp}}
      enabled: false   
{{else}} 
     enabled: true   
{{/if}} 
  env: 
  {{#each env}}
    - name: {{@key}}
      value: "{{this}}"
  {{/each}}
{{#if gcp}}
  webproxy: false
{{else}}
  webproxy: true
{{/if}} 
