no.nav:
  security.jwt.issuer.selvbetjening:
    discoveryurl: https://login.microsoftonline.com/NAVtestB2C.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1A_idporten_ver1
    accepted_audience: 0090b6e1-ffcc-4c37-bc21-049f7d1f0fe5

management:
    endpoints:
        web:
            exposure:
                include:  '*'
    endpoint:
        health:
            show-details: always

spring:
    mvc:
        log-request-details: true

virus:
  enabled: false
oppslag:
  uri:  https://api-gw-q1.oera.no/fpsoknad-oppslag/api/
historikk:
  uri: https://api-gw-q1.oera.no/fpinfo-historikk/api/
mottak:
  uri: https://api-gw-q1.oera.no/fpsoknad-mottak/api/
innsyn:
  mottak: https://api-gw-q1.oera.no/fpsoknad-mottak/api/
  oppslag: https://api-gw-q1.oera.no/fpsoknad-oppslag/api/
minidialog:
  uri: https://api-gw-q1.oera.no/fpinfo-historikk/api/
fppdfgen:
  uri: https://api-gw-q1.oera.no/fppdfgen/
