management:
   endpoints.web.exposure.include:  '*'
   endpoint :
      security.enabled : false
      health.show-details : always
      
spring.jackson.deserialization.fail-on-unknown-properties: true
               
       