allowed:
  origins:
    https://engangsstonad.nais.oera-q.local,
    https://engangsstonad-q.nav.no,
    https://foreldrepengesoknad.nais.oera-q.local,
    https://foreldrepengesoknad-q.nav.no,
    https://foreldrepengeoversikt.nais.oera-q.local,
    https://foreldrepenger-q.nav.no,
    https://svangerskapspengesoknad-q.nav.no
s3:
  url: http://objectstore.rook-ceph.svc.nais.local/
 
