allowed:
  origins:
   https://foreldrepengesoknad.dev.intern.nav.no,
   https://svangerskapspengesoknad.dev.intern.nav.no,
   https://foreldrepenger.dev.intern.nav.no,
   https://engangsstonad.dev.intern.nav.no,
   https://engangsstonadny.dev.intern.nav.no,
   https://foreldrepengesoknad.dev.intern.nav.no,
   https://svangerskapspengesoknad.dev.intern.nav.no,
   https://foreldrepenger.dev.intern.nav.no
spring:
  cloud:
    vault:
      enabled: false
no.nav:
   foreldrepenger:
      selvbetjening:
         api:
            virus:
               uri: http://clamav.clamav.svc.cluster.local 
