allowed:
  origins:
   https://foreldrepengesoknad.dev.nav.no,
   https://svangerskapspengesoknad.dev.nav.no,
   https://foreldrepenger.dev.nav.no,
   https://engangsstonad.dev.nav.no,
   https://foreldrepengeplanlegger.dev.nav.no,
   https://engangsstonadny.dev.nav.no,
   https://foreldrepengesoknad.dev.nav.no,
   https://foreldrepengesoknad.ekstern.dev.nav.no,
   https://svangerskapspengesoknad.dev.nav.no,
   https://foreldrepenger.dev.nav.no
spring:
  cloud:
    vault:
      enabled: false
virus:
   uri: http://clamav.clamav/scan
