management :
   endpoints.web.exposure.include:  '*'
   endpoint: 
     health.show-details : always
                   
no.nav.security.oidc:
  issuers: selvbetjening
  issuer.selvbetjening : 
     discoveryurl: http://metadata
     accepted_audience: aud-localhost
     cookie_name: localhost-idtoken
     
spring :
   http.log-request-details : true      
 
no.nav.foreldrepenger.selvbetjening.api.virus.enabled : false 
 
historikk :
  key: foreldrepengesoknad-api-historikk
  uri: http://localhost:9000/api/historikk
   
mottak:
  key: foreldrepengesoknad-api-mottak
  uri: http://localhost:9000/api/mottak
     
oppslag:
  key: foreldrepengesoknad-ap-oppslag
  uri: http://localhost:9000/api/oppslag
   
FORELDREPENGESOKNAD_API_S3_CREDS_PASSWORD: tøys
FORELDREPENGESOKNAD_API_S3_CREDS_USERNAME: tull
FORELDREPENGESOKNAD_API_S3_ENDPOINT_URL: some.host.somewhere
FORELDREPENGESOKNAD_API_STORAGE_PASSWORD: tullogtøys
TOGGLES_ENABLE_TPSBARN: true
