management :
   endpoints.web.exposure.include:  '*'
   endpoint: 
     health.show-details : always
     security.enabled : false
                   
no.nav.security.oidc:
  issuers: selvbetjening
  issuer.selvbetjening : 
     uri: http://metadata
     accepted_audience: aud-localhost
     cookie_name: localhost-idtoken