management:
   endpoints.web.exposure.include:  '*'
   endpoint :
      security.enabled : false
      health.show-details : always
      
spring :
    http.log-request-details : true      
    jackson.deserialization.fail-on-unknown-properties: false
               
       