allowed:
  origins:
   https://foreldrepengesoknad.intern.nav.no,
   https://svangerskapspengesoknad.intern.nav.no,
   https://foreldrepenger.intern.nav.no,
   https://engangsstonad.intern.nav.no,
   https://foreldrepengeplanlegger.intern.nav.no,
   https://foreldrepengesoknad.intern.nav.no,
   https://svangerskapspengesoknad.intern.nav.no,
   https://foreldrepenger.intern.nav.no
spring:
  cloud:
    vault:
      enabled: false

mellomlagring:
  tmp:
    navn: foreldrepengesoknad-prod
  søknad:
     navn: mellomlagring-prod

virus:
   uri: http://clamav.clamav/scan
