allowed:
  origins:
    https://engangsstonad.nais.oera-q.local,
    https://engangsstonad-q.nav.no,
    https://foreldepengeplanlegger-q.nav.no,
    https://foreldrepengesoknad.nais.oera-q.local,
    https://foreldrepengesoknad-q.nav.no,
    https://foreldrepengeoversikt.nais.oera-q.local,
    https://foreldrepenger-q.nav.no,
    https://svangerskapspengesoknad-q.nav.no
s3:
  url: http://objectstore.rook-ceph.svc.nais.local/
spring:
  config.import: vault://
  cloud:
      vault:
         reactive:
           enabled: false
         enabled: true 
         uri: https://vault.adeo.no
         authentication: KUBERNETES
         kubernetes:
            role: foreldrepengesoknad-api
            kubernetes-path: kubernetes/preprod/sbs
            service-account-token-file: /var/run/secrets/kubernetes.io/serviceaccount/token        
         kv:
            enabled: true
            backend: kv/preprod/sbs
            application-name: foreldrepengesoknad-api/teamforeldrepenger
            default-context: foreldrepengesoknad-api/teamforeldrepenger
 
