allowed:
  origins:
   https://engangsstonad.nav.no,
   https://foreldrepengesoknad.nav.no,
   https://svangerskapspengesoknad.nav.no,
   https://foreldrepenger.nav.no
no.nav:
   security:
    jwt:
      issuer:
        selvbetjening:
           discoveryurl: ${loginservice.idporten.discovery.url}
           accepted_audience: ${loginservice.idporten.audience}  
           cookie_name: selvbetjening-idtoken
   
   foreldrepenger:
      selvbetjening:
         api:
            virus:
               enabled: true
       
management:
   metrics:
      web:
        server:
           request:
             autotime:
                 enabled: true
   health :
      refresh:
         enabled: false
      diskspace:
         enabled: false
   endpoint:
      health:
         show-details : never
   endpoints:
      web:
         exposure:
            include: info, health, metrics, prometheus
         base-path: /internal/actuator
server:
   servlet:
      context-path: /
   forward-headers-strategy: native
   error:
      whitelabel:
         enabled: false
spring:
   cache:
      cache-names: aktør
      caffeine:
         spec: maximumSize=100,expireAfterAccess=3600s
   application:
      name: foreldrepengesoknad-api
   jackson:
      default-property-inclusion: non-absent
      mapper:
         accept-case-insensitive-properties: true
      deserialization:
         accept-single-value-as-array: true
         fail-on-unknown-properties: false
      serialization:
         fail-on-empty-beans: false
   main:
      banner-mode: 'off'
   servlet:
      multipart:
         max-file-size: 100MB
         max-request-size: 100MB
   mvc:
      throw-exception-if-no-handler-found: true
