management :
   endpoints.web.exposure.include:  '*'
   endpoint: 
     health.show-details : always
                   
no.nav.security.oidc:
  issuer.selvbetjening : 
     discoveryurl: http://metadata
     accepted_audience: aud-localhost
     cookie_name: localhost-idtoken
     
spring :
   http.log-request-details : true      
 
no.nav:
  foreldrepenger.selvbetjening.api.virus.enabled : false 
 
historikk :
  key: foreldrepengesoknad-api-historikk
  uri: http://localhost:9000/api/historikk
   
mottak:
  key: foreldrepengesoknad-api-mottak
  uri: http://localhost:9000/api/mottak
     
oppslag:
  key: foreldrepengesoknad-ap-oppslag
  uri: http://localhost:9000/api/oppslag
   
s3 : 
  username : user
  password : pwd
  url : some.host.somewhere
storage :
  passphrase: tullogtøys