allowed.origins: '*'
debug: false
management :
   endpoints:
     web:
       exposure:
         include:  '*'
   endpoint:
     health:
       show-details : always
no.nav.security.jwt:
  issuer.selvbetjening :
     discoveryurl: http://metadata
     accepted_audience: aud-localhost
     cookie_name: localhost-idtoken

spring :
   mvc:
     log-request-details : true

no.nav:
  foreldrepenger:
    selvbetjening:
      api:
        virus:
          enabled : false
        
fppdfgen:
   uri: http://localhost:8080/api/v1/genpdf
   enabled: false
          
historikk :
  key: foreldrepengesoknad-api-historikk
  uri: http://localhost:9000/api
  enabled: false

mottak:
  key: foreldrepengesoknad-api-mottak
  uri: http://localhost:9000/api/mottak
  enabled: false

oppslag:
  key: foreldrepengesoknad-ap-oppslag
  uri: http://localhost:9000/api/oppslag
  enabled: false

minidialog:
  uri: http://localhost:9000/api
  enabled: false
innsyn:
  oppslag:  http://localhost:9000/api/oppslag
  mottak:  http://localhost:9000/api/mottak
  enabled: false

s3 :
  username : user
  password : pwd
  url : some.host.somewhere
storage :
  passphrase: tullogtøys
