info.app:
    version: '@project.version@'
    build.time:  '@timestamp@' 
management:
   endpoints.web.exposure.include:  info, health, metrics, prometheus
   endpoints.web.base-path: /internal/actuator
server:
  servlet.context-path: /
  use-forward-headers: true
spring :
  jackson.deserialization.accept_single_value_as_array: true
  main.banner-mode: 'off'
  metrics.web.server.auto-time-requests: true
  servlet.multipart.max-file-size: 9MB
no.nav.security.oidc:
  issuers: selvbetjening
  issuer.selvbetjening:
    discoveryurl: <Set from Fasit>
    accepted_audience: <Set from Fasit>
    cookie_name: selvbetjening-idtoken
