info.app:
    version: '@project.version@'
    build.time:  '@timestamp@'
management:
   endpoints.web.exposure.include:  info, health, metrics, prometheus
server:
  servlet.context-path: /foreldrepengesoknad-api
  use-forward-headers: true
spring :
  main.banner-mode: 'off'
  metrics.web.server.auto-time-requests: true
  servlet.multipart.max-file-size: 9MB
no.nav.security.oidc:
  issuers: selvbetjening
  issuer.selvbetjening:
    uri: <Set from Fasit>
    accepted_audience: <Set from Fasit>
    cookie_name: selvbetjening-idtoken
http.proxy: http://webproxy-utvikler.nav.no:8088
