allowed.origins: '*'
debug: false
management :
   endpoints:
     web:
       exposure:
         include:  '*'
   endpoint: 
     health:
       show-details : always
                   
no.nav.security.jwt:
  issuer.selvbetjening : 
     discoveryurl: http://metadata
     accepted_audience: aud-localhost
     cookie_name: localhost-idtoken
     
spring :
   http:
     log-request-details : true      

no.nav:
  foreldrepenger:
    selvbetjening:
      api:
        virus:
          enabled : false 
 
historikk :
  key: foreldrepengesoknad-api-historikk
  uri: http://localhost:9000/api
   
mottak:
  key: foreldrepengesoknad-api-mottak
  uri: http://localhost:9000/api/mottak
     
oppslag:
  key: foreldrepengesoknad-ap-oppslag
  uri: http://localhost:9000/api/oppslag
  
minidialog:
  uri: http://localhost:9000/api
innsyn:
  oppslag:  http://localhost:9000/api/oppslag
  mottak:  http://localhost:9000/api/mottak
  enabled: true
   
s3 : 
  username : user
  password : pwd
  url : some.host.somewhere
storage :
  passphrase: tullogtøys