allowed:
  origins:
   https://engangsstonad.dev.nav.no,
   https://foreldrepengesoknad.dev.nav.no,
   https://foreldrepengesoknad.dev.adeo.no,
   https://svangerskapspengesoknad.dev.nav.no,
   https://foreldrepenger.dev.nav.no,
   https://engangsstonad.dev.nav.no,
   https://foreldrepengesoknad.dev.nav.no,
   https://svangerskapspengesoknad.dev.nav.no,
   https://foreldrepenger.dev.nav.no

no.nav:
   foreldrepenger:
      selvbetjening:
         api:
            virus:
               uri: http://clamav.clamav.svc.cluster.local

fppdfgen:
   uri: http://fppdfgen
