oppslag:
  uri: https://api-gw.oera.no/fpsoknad-mottak/api/
historikk:
  uri: https://api-gw.oera.no/fpinfo-historikk/api/
mottak:
  uri: https://api-gw.oera.no/fpsoknad-mottak/api/
innsyn:
  uri: https://api-gw.oera.no/fpsoknad-mottak/api/
minidialog:
  uri: https://api-gw.oera.no/fpinfo-historikk/api/
fppdfgen:
  uri: https://api-gw.oera.no/fppdfgen/
