no.nav:
   foreldrepenger:
      selvbetjening:
         api:
           virus:
             enabled: true 
   security.oidc:
      issuers: selvbetjening
      issuer:
         selvbetjening:
           cookie_name: selvbetjening-idtoken   
info:
   app:
     version: '@project.version@'
     build:
        time: '@timestamp@'
management:
  metrics:
     web:
        server:
           auto-time-requests : true
  endpoints:
      web:
         exposure:
            include:  info, health, metrics, prometheus
         base-path: /internal/actuator
server:
  servlet:
     context-path: /
  use-forward-headers: true
  error:
     whitelabel:
        enabled: false
spring:
  cache:
     cache-names: aktoer
     caffeine:
        spec: maximumSize=100,expireAfterAccess=3600s
  application:
     name: foreldrepengesoknad-api
  jackson :
      default-property-inclusion :  non-absent
      mapper :
         accept-case-insensitive-properties: true
      deserialization :
         accept-single-value-as-array: true
         fail-on-unknown-properties: false
      serialization :
         fail-on-empty-beans: false
  main:
     banner-mode: 'off'
  servlet:
     multipart:
        max-file-size: 100MB
        max-request-size: 100MB
  mvc:
     throw-exception-if-no-handler-found: true
  resources:
     add-mappings: false
  
 