version: 2.1
orbs:
  nais: navikt/nais-deployment@1.4.1
  slack: circleci/slack@3.3.0
  
jobs:
   build:
     working_directory: ~/foreldrepengesoknad-api
     docker:
       - image: circleci/openjdk:11-jdk
     steps:
     
       - checkout  
        
       - restore_cache: 
          name: Hente cache 
          key: foreldrepengesoknad-api-{{ checksum "pom.xml" }}
      
       - run:
          name: Lagre avhengigheter  
          command : mvn dependency:go-offline
      
       - save_cache:
          paths:
            - ~/foreldrepengesoknad-api/.m2
          key: foreldrepengesoknad-api-{{ checksum "pom.xml" }}
          
       - run: 
           machine: true
           name: Bygge 
           command: mvn clean package 
      
       - run:
           name: Flytte testresultater
           command: |
             mkdir -p ~/test-results/junit/
             find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
           when: always

       - store_test_results:
          path: ~/test-results

       - store_artifacts:
          path: ~/test-results/junit  
          
       - nais/docker-deploy:
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME	
          
workflows:
   version: 2
   deploy-nais:
     jobs:
      - build:
          context: NAIS deployment 
                            
      - nais/deploy:
          name: dev-sbs-deploy
          enable-vars: true
          template-vars: api-prod-sbs.json
          build-and-push-docker-image: false
          context: NAIS deployment
          repo: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          github-app-id: 20250
          nais-template: naiserator.yaml
          environment: dev-sbs
          team: teamforeldrepenger
          filters:
            branches:
              only: master
          requires:
            - build
            
      - hold:
          type: approval
          filters:
            branches:
              only: master
          requires:
            - dev-sbs-deploy 
              
      - slack/approval-notification:
           webhook: $SLACK
           message: "Godkjenn deploy til prod-sbs av $CIRCLE_PROJECT_REPONAME"
           url: https://circleci.com/workflow-run/$CIRCLE_WORKFLOW_WORKSPACE_ID
           requires:
            - dev-sbs-deploy 
                   
      - nais/deploy:
          name: prod-sbs-deploy
          enable-vars: true
          template-vars: api-prod-sbs.json
          build-and-push-docker-image: false
          context: NAIS deployment
          repo: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          github-app-id: 20250
          nais-template: naiserator.yaml
          environment: prod-sbs
          team: teamforeldrepenger
          filters:
            branches:
              only: master
          requires:
            - hold       
              
