name: Build PR or branch

on:
  pull_request:
  push:
    branches-ignore:
      - master
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  IMAGE_BASE: ghcr.io/${{ github.repository }}

jobs:
  kompiler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
          check-latest: true
          cache: 'maven'
      - name: Kompiler
        run: |
          mvn install --batch-mode --quiet --settings .github/.m2/settings.xml
