name: Deployment pipeline q1

on:
  push:
    branches:
      - master
env:
  SONAR: ${{ secrets.SONAR }}   
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CLUSTER: dev-sbs
  IMAGE_BASE: docker.pkg.github.com/${{ github.repository }}/foreldrepengesoknad-api
  
jobs:
  kompiler:
    runs-on: ubuntu-latest
    steps:
    
      - name: Sjekk ut kode
        uses: actions/checkout@v2
     
      - name: Hent tag    
        run: echo "::set-env name=TAG::$(git log -1 --pretty='%ad' --date=format:'%Y%m%d%H%M%S')-$(echo $GITHUB_SHA | cut -c1-7)"  
             
      - name: Hent maven version    
        run: |
          echo "::set-env name=MVN_VERSION::$(mvn help:evaluate -Dsha1=${TAG} -Dexpression=project.version -q -DforceStdout)"
                  
      - name: Hent Maven cache
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
  
      - name: Sett opp Java 11      
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
    
      - name: Kompiler
        run: | 
          mvn versions:set -DnewVersion=${MVN_VERSION}
          echo "::set-env name=IMAGE::$IMAGE_BASE:$TAG" 
          mvn --quiet jacoco:prepare-agent install jacoco:report sonar:sonar  -e --batch-mode   -Dsonar.login=${SONAR} -Djacoco.destFile=$(pwd)/target/jacoco.exec
  #       mvn clean install --batch-mode --quiet 
                   
      - name: Bygg, tag og push Docker image  
        run: |
          docker build --tag ${IMAGE} --tag ${IMAGE_BASE}:latest .
          echo  ${GITHUB_TOKEN} | docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} --password-stdin
          docker push ${IMAGE_BASE}  
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          tag_name: ${{ env.MVN_VERSION }}
          release_name: Release ${{ env.MVN_VERSION }}
          draft: false
          prerelease: false         
    
      - name: Opprett deployment issue
        if: success()
        uses: maxkomarychev/oction-create-issue@v0.7.1
        id: createdeployissue
        with:
          token: ${{ secrets.NOTIFICATION }}
          title: Deploy av ${{ env.TAG }}
          labels: ${{env.CLUSTER}}
          body: |
            Kommenter med <b>/promote ${{ env.TAG }} cluster</b>, hvor <b>cluster</b> er et gyldig clusternavn
            <table>
            <tr><th>Cluster</th></tr>
            <tr><td>dev-sbs</td></tr>
            <tr><td>dev-gcp</td></tr>
            <tr><td>prod-gcp</td></tr>
            <tr><td>prod-sbs</td></tr>
            </table>
      
      - name: Trigg deploy til dev-sbs
        if: success()
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.NOTIFICATION }}
          issue-number: ${{ steps.createdeployissue.outputs.number }}
          body: /promote ${{ env.TAG }} ${{ env.CLUSTER }}
    
      - name: Trigg deploy til dev-gcp
        if: success()
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.NOTIFICATION }}
          issue-number: ${{ steps.createdeployissue.outputs.number }}
          body: /promote ${{ env.TAG }} dev-gcp
     
